# Generated by Django 6.1.1 on 2026-09-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_carrinho_carrinhoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='favoritado_por', to='loja.produto'),
        ),
    ]
